# EVN

In [1]:
import numpy as np
import matplotlib.pyplot as plt

import tensorflow as tf

# 행렬연산

## 데이터

In [2]:
hidden = np.random.randint(-9, 10, (5, 4)) / 10
hidden

array([[-0.8,  0.1, -0.6, -0.7],
       [ 0.4,  0.1, -0.7, -0.5],
       [-0.6, -0.8, -0.4, -0.5],
       [ 0.3, -0.9, -0.3, -0.5],
       [-0.7,  0.4,  0.4, -0.2]])

## element wise sum

In [3]:
arg = np.random.randint(-9, 10, (5, 4)) / 10
arg, hidden + arg

(array([[ 0.9,  0.1, -0.7, -0.2],
        [ 0.8,  0.3, -0.1, -0.3],
        [ 0.3,  0.2,  0.6,  0.1],
        [ 0.1,  0.2,  0.3, -0.4],
        [ 0.5,  0.6,  0.3, -0.8]]), array([[ 0.1,  0.2, -1.3, -0.9],
        [ 1.2,  0.4, -0.8, -0.8],
        [-0.3, -0.6,  0.2, -0.4],
        [ 0.4, -0.7,  0. , -0.9],
        [-0.2,  1. ,  0.7, -1. ]]))

In [4]:
arg = np.random.randint(-9, 10, (1, 4)) / 10
arg, hidden + arg

(array([[-0.9,  0.6, -0.1, -0.4]]), array([[-1.7,  0.7, -0.7, -1.1],
        [-0.5,  0.7, -0.8, -0.9],
        [-1.5, -0.2, -0.5, -0.9],
        [-0.6, -0.3, -0.4, -0.9],
        [-1.6,  1. ,  0.3, -0.6]]))

In [5]:
arg = np.random.randint(-9, 10, (5, 1)) / 10
arg, hidden + arg

(array([[-0.7],
        [ 0.3],
        [ 0.1],
        [ 0.9],
        [-0.1]]), array([[-1.5, -0.6, -1.3, -1.4],
        [ 0.7,  0.4, -0.4, -0.2],
        [-0.5, -0.7, -0.3, -0.4],
        [ 1.2,  0. ,  0.6,  0.4],
        [-0.8,  0.3,  0.3, -0.3]]))

In [6]:
arg = np.random.randint(-9, 10, (1, 1)) / 10
arg, hidden + arg

(array([[-0.2]]), array([[-1. , -0.1, -0.8, -0.9],
        [ 0.2, -0.1, -0.9, -0.7],
        [-0.8, -1. , -0.6, -0.7],
        [ 0.1, -1.1, -0.5, -0.7],
        [-0.9,  0.2,  0.2, -0.4]]))

In [7]:
hidden + 1

array([[0.2, 1.1, 0.4, 0.3],
       [1.4, 1.1, 0.3, 0.5],
       [0.4, 0.2, 0.6, 0.5],
       [1.3, 0.1, 0.7, 0.5],
       [0.3, 1.4, 1.4, 0.8]])

In [8]:
1 + hidden

array([[0.2, 1.1, 0.4, 0.3],
       [1.4, 1.1, 0.3, 0.5],
       [0.4, 0.2, 0.6, 0.5],
       [1.3, 0.1, 0.7, 0.5],
       [0.3, 1.4, 1.4, 0.8]])

## element wise multiplication

In [9]:
arg = np.random.randint(-9, 10, (5, 4)) / 10
arg, hidden * arg

(array([[-0.1, -0.3,  0.4,  0.5],
        [-0.5,  0.1,  0.7,  0.8],
        [-0.3,  0.4, -0.4,  0.8],
        [-0.8, -0.7,  0.4, -0.5],
        [ 0.3, -0.9,  0.1,  0.7]]), array([[ 0.08, -0.03, -0.24, -0.35],
        [-0.2 ,  0.01, -0.49, -0.4 ],
        [ 0.18, -0.32,  0.16, -0.4 ],
        [-0.24,  0.63, -0.12,  0.25],
        [-0.21, -0.36,  0.04, -0.14]]))

In [10]:
arg = np.random.randint(-9, 10, (1, 4)) / 10
arg, hidden * arg

(array([[ 0.6, -0.2, -0.8,  0.5]]), array([[-0.48, -0.02,  0.48, -0.35],
        [ 0.24, -0.02,  0.56, -0.25],
        [-0.36,  0.16,  0.32, -0.25],
        [ 0.18,  0.18,  0.24, -0.25],
        [-0.42, -0.08, -0.32, -0.1 ]]))

In [11]:
arg = np.random.randint(-9, 10, (5, 1)) / 10
arg, hidden * arg

(array([[-0.2],
        [ 0.4],
        [-0.1],
        [ 0.5],
        [ 0. ]]), array([[ 0.16, -0.02,  0.12,  0.14],
        [ 0.16,  0.04, -0.28, -0.2 ],
        [ 0.06,  0.08,  0.04,  0.05],
        [ 0.15, -0.45, -0.15, -0.25],
        [-0.  ,  0.  ,  0.  , -0.  ]]))

In [12]:
arg = np.random.randint(-9, 10, (1, 1)) / 10
arg, hidden * arg

(array([[-0.6]]), array([[ 0.48, -0.06,  0.36,  0.42],
        [-0.24, -0.06,  0.42,  0.3 ],
        [ 0.36,  0.48,  0.24,  0.3 ],
        [-0.18,  0.54,  0.18,  0.3 ],
        [ 0.42, -0.24, -0.24,  0.12]]))

In [13]:
hidden * 2

array([[-1.6,  0.2, -1.2, -1.4],
       [ 0.8,  0.2, -1.4, -1. ],
       [-1.2, -1.6, -0.8, -1. ],
       [ 0.6, -1.8, -0.6, -1. ],
       [-1.4,  0.8,  0.8, -0.4]])

In [14]:
2 * hidden

array([[-1.6,  0.2, -1.2, -1.4],
       [ 0.8,  0.2, -1.4, -1. ],
       [-1.2, -1.6, -0.8, -1. ],
       [ 0.6, -1.8, -0.6, -1. ],
       [-1.4,  0.8,  0.8, -0.4]])

## matrix multiplication

In [15]:
arg = np.random.randint(-9, 10, (4, 5)) / 10
arg, np.matmul(hidden, arg)

(array([[ 0.6,  0.3, -0.1, -0.2, -0.2],
        [ 0.2, -0.5,  0.1, -0.8, -0.1],
        [ 0.1, -0.7,  0.2,  0.7, -0.1],
        [ 0.4, -0.5, -0.7,  0.4,  0.4]]),
 array([[-0.8 ,  0.48,  0.46, -0.62, -0.07],
        [-0.01,  0.81,  0.18, -0.85, -0.22],
        [-0.76,  0.75,  0.25,  0.28,  0.04],
        [-0.23,  1.  ,  0.17,  0.25, -0.14],
        [-0.38, -0.59,  0.33,  0.02, -0.02]]))

In [16]:
val = np.zeros((hidden.shape[0], arg.shape[1]))
val

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
for row in range(hidden.shape[0]):
    row_v = hidden[row]
    for col in range(arg.shape[1]):
        col_v = arg[:, col]
        val[row][col] = np.dot(row_v, col_v)
val

array([[-0.8 ,  0.48,  0.46, -0.62, -0.07],
       [-0.01,  0.81,  0.18, -0.85, -0.22],
       [-0.76,  0.75,  0.25,  0.28,  0.04],
       [-0.23,  1.  ,  0.17,  0.25, -0.14],
       [-0.38, -0.59,  0.33,  0.02, -0.02]])